export default {
  CONTACTS_LIST: 'CONTACTS_LIST',
  SELECTED_CONTACT: 'SELECTED_CONTACT',
  VIEW_MODAL_FIELD_EDIT: 'VIEW_MODAL_FIELD_EDIT',
  CURRENT_FIELD_TO_EDIT: 'CURRENT_FIELD_TO_EDIT',
  SET_TIME_LAPSE: 'SET_TIME_LAPSE',
  PUSH_TIME_LAPSE: 'PUSH_TIME_LAPSE',
};
